apiVersion: v1
kind: Pod
metadata:
  name: relayed-pod
spec:
  initContainers:
    - name: qtap-init
      image: us-docker.pkg.dev/qpoint-edge/public/kubernetes-qpoint-init:<SHA>
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  containers:
    - name: app
      image: ubuntu:latest
      command:
        - /bin/sh
        - -c
        - |
          adduser --uid 1002 --disabled-password --gecos "" testuser
          apt-get update
          apt-get -y install curl net-tools
          while true; do
            # Keep container alive indefinitely
            sleep 3600
          done
    - name: proxy
      image: us-docker.pkg.dev/qpoint-edge/public/qtap:<SHA>
      ports:
        - containerPort: 10080
        - containerPort: 10443
        - containerPort: 18080
        - containerPort: 18443
      command: ["qpoint"]
      args: ["proxy", "--envoy-log-level=error", "--log-level=info", "--dns-lookup-family=V4_ONLY"]
      env:
        - name: REGISTRATION_TOKEN
          value: "<TOKEN>"
