apiVersion: v1
kind: Pod
metadata:
  name: relayed-pod
spec:
  initContainers:
    - name: qpoint-init
      image: us-docker.pkg.dev/qpoint-edge/public/kubernetes-qpoint-init:<SHA>
      env:
        - name: TO_ADDR
          value: "192.168.1.1"
        - name: PORT_MAPPING
          value: "10080:80,10443:443"
        - name: ACCEPT_UIDS
          value: "0"
        - name: ACCEPT_GIDS
          value: "0"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  containers:
    - name: app
      image: ubuntu:latest
      command:
        - /bin/sh
        - -c
        - |
          adduser --uid 1002 --disabled-password --gecos "" testuser
          apt-get update
          apt-get -y install curl
          while true; do
            # Keep container alive indefinitely
            sleep 3600
          done
