name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current branch
        id: get_branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          fi
          echo "Current branch is: $BRANCH_NAME"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: us-docker.pkg.dev/qpoint-edge/public/kubernetes-qtap-init
          tags: |
            type=sha
            type=raw,value=branch-${{ env.BRANCH_NAME }},enable=${{ env.BRANCH_NAME != 'main' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
